{% set name = "poppy" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/poppy-{{ version }}.tar.gz
  sha256: 37afe1fc24eb31e6799a3110fa0189afac65d624e4e1d19036e6378483591969

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools >=38.0.0
    - setuptools-scm >=2.0.0
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy >=1.18.0
    - scipy >=1.5.0
    - matplotlib-base >=3.2.0
    - astropy-base >=4.0.0

test:
  imports:
    - poppy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://poppy-optics.readthedocs.io/
  summary: Physical optics propagation (wavefront diffraction) for optical simulations, particularly of telescopes.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jaimergp
    - goanpeca
